import { createRequire } from "node:module";
import { API_VERSION } from "./scanDtos.mjs";

const require = createRequire(import.meta.url);
const appPackage = require("../package.json");
const corePackage = require("../packages/core/package.json");

export function buildCapabilitiesPayload({
  authenticated,
  allowUnauthenticated,
  scanTimeoutMs,
  deepPassiveScanTimeoutMs,
  scanConcurrency,
  monitoringScheduler,
  notifications,
  alerts,
  serveFrontend,
} = {}) {
  return {
    apiVersion: API_VERSION,
    service: {
      name: "SecURL API",
      appVersion: appPackage.version,
      corePackage: corePackage.name,
      coreVersion: corePackage.version,
      serveFrontend: Boolean(serveFrontend),
      resources: [
        "GET /api/health",
        "GET /api/ready",
        "GET /api/capabilities",
        "GET /api/product-pulse",
        "GET /api/certificates/live?url=:url",
      ],
      clientTelemetry: {
        optional: true,
        privacySafe: true,
        headers: {
          client: "X-SecURL-Client",
          version: "X-SecURL-Client-Version",
          channel: "X-SecURL-Client-Channel",
        },
        channels: ["app-store", "testflight", "development", "automation"],
      },
    },
    auth: {
      methods: [
        ...(authenticated ? ["api-key"] : []),
        "bearer-session",
        ...(allowUnauthenticated ? ["scan-owner"] : []),
      ],
      anonymousScanOwner: Boolean(allowUnauthenticated),
      resources: [
        "POST /api/auth/register",
        "POST /api/auth/login",
        "GET /api/auth/session",
        "POST /api/auth/logout",
        "GET /api/auth/api-keys",
        "POST /api/auth/api-keys",
        "DELETE /api/auth/api-keys/:id",
      ],
    },
    scans: {
      modes: ["standard", "quiet", "deep-passive"],
      statuses: ["queued", "running", "completed", "failed"],
      features: [
        "executive-summary",
        "finding-evidence",
        "evidence-summary",
        "evidence-quality",
        "remediation-plan",
        "posture-digest",
        "posture-insights",
        "signal-clarity",
        "mobile-scan-summary",
        "posture-drift",
        "exposure-brief",
        "vendor-exposure",
        "action-plan",
        "scan-events",
        "scan-resource-links",
        "durable-scan-jobs",
        "observation-ledger-v1",
        "observation-drift-v1",
        "observation-policy-v1",
      ],
      scoring: {
        model: "weighted-passive-posture",
        version: "2026-06-14",
        gradeScale: ["A+", "A", "B", "C", "D", "F", "U"],
        scoreRange: {
          min: 0,
          max: 100,
        },
      },
      maxDurationMs: {
        standard: scanTimeoutMs,
        quiet: scanTimeoutMs,
        deepPassive: deepPassiveScanTimeoutMs,
      },
      concurrency: scanConcurrency,
      policy: {
        defaultId: "securl-baseline-v1",
        maxRules: 25,
        scopes: ["observation", "change"],
        operators: ["eq", "neq", "in", "gte", "lte"],
      },
      resources: [
        "POST /api/scans",
        "GET /api/scans",
        "GET /api/scans?url=:url",
        "GET /api/scans/:id",
        "GET /api/scans/:id/summary",
        "GET /api/scans/:id/findings",
        "GET /api/scans/:id/digest",
        "GET /api/scans/:id/insights",
        "GET /api/scans/:id/mobile-summary",
        "GET /api/scans/:id/brief",
        "GET /api/scans/:id/vendors",
        "GET /api/scans/:id/action-plan",
        "GET /api/scans/:id/evidence",
        "GET /api/scans/:id/observations",
        "GET /api/scans/:id/observation-drift",
        "GET /api/scans/:id/policy-evaluation",
        "GET /api/scans/:id/history",
        "GET /api/scans/:id/comparison",
        "GET /api/scans/:id/drift",
        "GET /api/scans/:id/export?format=json|markdown|sarif|ci-json",
        "GET /api/scans/:id/share",
        "GET /api/scans/:id/events",
      ],
    },
    certificates: {
      features: [
        "live-certificate",
        "tls-handshake-only",
        "cert-attention-state",
        "cert-event-context-v1",
        "cert-history-context-v1",
      ],
      resources: [
        "GET /api/certificates/live?url=:url",
      ],
    },
    monitoring: {
      enabled: true,
      kinds: ["posture", "cert"],
      cadences: ["hourly", "6h", "daily", "weekly"],
      features: [
        "scheduled-posture-monitoring",
        "scheduled-cert-monitoring",
        "manual-run",
        "target-history",
        "mobile-summary",
        "mobile-posture-drift-summary",
        "mobile-digest-preview",
        "mobile-signal-clarity",
        "mobile-monitoring-status-v1",
        "mobile-monitoring-actions-v1",
        "monitoring-health-v1",
        "cert-watchlist-summary-v1",
        "cert-watchlist-push-health-v1",
        "cert-attention-state",
        "target-observation-policy",
      ],
      scheduler: {
        enabled: Boolean(monitoringScheduler?.enabled),
        mode: monitoringScheduler?.mode ?? "quiet",
        intervalMs: monitoringScheduler?.intervalMs ?? null,
        limit: monitoringScheduler?.limit ?? null,
        lastSweep: monitoringScheduler?.lastSweep ?? null,
      },
      resources: [
        "POST /api/monitoring-targets",
        "GET /api/monitoring-targets",
        "GET /api/monitoring-health",
        "GET /api/monitoring-summary",
        "GET /api/monitoring-cert-summary",
        "GET /api/monitoring-mobile-summary",
        "GET /api/monitoring-targets/:id",
        "GET /api/monitoring-targets/:id/history",
        "POST /api/monitoring-targets/:id/run",
        "DELETE /api/monitoring-targets/:id",
      ],
    },
    notifications: {
      providers: ["apns"],
      enabled: Boolean(notifications?.enabled),
      delivery: {
        timeoutMs: notifications?.timeoutMs ?? null,
        maxAttempts: notifications?.maxAttempts ?? null,
        invalidTokenReasons: ["Unregistered", "BadDeviceToken", "DeviceTokenNotForTopic"],
        retries: ["network_error", "timeout", "apns_429", "apns_5xx"],
      },
      outbox: {
        enabled: Boolean(notifications?.outbox?.enabled),
        lastDrain: notifications?.outbox?.lastDrain ?? null,
      },
      features: [
        "device-registration",
        "device-health",
        "delivery-audit",
        "test-notification",
        "bounded-delivery-retry",
        "durable-notification-outbox",
        "monitoring-drift-push",
        "cert-event-push",
      ],
      resources: [
        "GET /api/notification-devices",
        "GET /api/notification-devices/health",
        "POST /api/notification-devices",
        "POST /api/notification-devices/:id/test",
        "DELETE /api/notification-devices/:id",
      ],
    },
    alerts: {
      enabled: Boolean(alerts?.enabled),
      channels: alerts?.channels ?? { apns: false, webhook: true, email: false },
      features: [
        "policy-violation-alerts",
        "policy-alert-brief-v1",
        "policy-alert-actions-v1",
        "new-violation-deduplication",
        "durable-alert-outbox",
        "signed-webhooks",
        "bounded-delivery-retry",
        "destination-test",
      ],
      resources: [
        "GET /api/alert-destinations",
        "POST /api/alert-destinations",
        "POST /api/alert-destinations/:id/test",
        "DELETE /api/alert-destinations/:id",
      ],
      outbox: { lastDrain: alerts?.lastDrain ?? null },
    },
    exports: {
      formats: ["json", "markdown", "sarif", "ci-json"],
      shareLinks: true,
    },
    safety: {
      passiveFirst: true,
      publicTargetsOnly: true,
      blocksPrivateNetworkTargets: true,
    },
  };
}
