import { Activity, Clock3, Layers3, Sparkles } from "lucide-react";
import { GRADE_PALETTE } from "@/components/SecurityGrade";
import { toast } from "sonner";
import { AuthCard } from "@/components/AuthCard";
import { MonitoredTargetsPanel } from "@/components/MonitoredTargetsPanel";
import { UrlForm } from "@/components/UrlForm";
import { buildReportWorkspaceSections } from "@/lib/reportWorkspace";
import { ReportSectionNav } from "@/components/report/ReportSectionNav";
import { useAuthSession } from "@/hooks/useAuthSession";
import { useScanWorkspace } from "@/hooks/useScanWorkspace";
import { AppStoreBadge } from "@/components/AppStoreBadge";
import { AndroidDownloadsBadge } from "@/components/AndroidDownloadsBadge";
import { recordTelemetryEvent } from "@/lib/apiClient";
import { buildReportShareUrl } from "@/lib/deepLinks";
import { HERO_SAMPLE, type HeroSampleChip } from "@/data/heroSample";

// ── Mini ring preview (hero right column, pre-scan) ──────────────────────────
// The sample card shows a real standard-mode SecURL grade (src/data/heroSample.ts,
// generated by `npm run snapshot:hero-sample`) — never a fabricated one. All
// styling is derived from the grade, so refreshing the snapshot never touches CSS.
const MINI_R    = 74;
const MINI_SIZE = 174;
const MINI_CIRC = parseFloat((2 * Math.PI * MINI_R).toFixed(2));

const sampleChipStyle = (sev: HeroSampleChip["sev"]) => {
  if (sev === "critical")
    return { background: "rgba(239,68,68,0.10)", borderColor: "rgba(239,68,68,0.25)", color: "#fca5a5" };
  if (sev === "warning")
    return { background: "rgba(217,119,6,0.10)", borderColor: "rgba(217,119,6,0.25)", color: "#fbbf24" };
  return { background: "rgba(100,116,139,0.08)", borderColor: "rgba(100,116,139,0.20)", color: "#94a3b8" };
};

const HeroPreviewCard = () => {
  const palette = GRADE_PALETTE[HERO_SAMPLE.grade] ?? GRADE_PALETTE.U;
  const miniOffset = parseFloat((MINI_CIRC * (1 - HERO_SAMPLE.score / 100)).toFixed(2));

  return (
    <div className="relative h-full overflow-hidden rounded-[1.8rem] border border-white/10 bg-zinc-950/35 p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] sm:p-6">
      {/* Grade glow */}
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          background: `radial-gradient(ellipse 260px 200px at 50% 38%, ${palette.glow} 0%, transparent 70%)`,
        }}
      />

      {/* Label */}
      <div className="relative mb-4 flex items-center justify-between">
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-zinc-500">Sample result</p>
        <span
          className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-[0.12em]"
          style={{ color: palette.textColor, borderColor: palette.borderColor, background: `${palette.stroke}1a` }}
        >
          Grade {HERO_SAMPLE.grade}
        </span>
      </div>

      {/* Ring */}
      <div className="relative flex flex-col items-center">
        <div className="relative" style={{ width: MINI_SIZE, height: MINI_SIZE }}>
          <div
            className="pointer-events-none absolute inset-0 rounded-full"
            style={{ boxShadow: `0 0 48px 0 ${palette.glow}` }}
          />
          <svg
            viewBox={`0 0 ${MINI_SIZE} ${MINI_SIZE}`}
            width={MINI_SIZE}
            height={MINI_SIZE}
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx={MINI_SIZE / 2} cy={MINI_SIZE / 2} r={MINI_R}
              fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="14"
            />
            <circle
              cx={MINI_SIZE / 2} cy={MINI_SIZE / 2} r={MINI_R}
              fill="none" stroke={palette.stroke} strokeWidth="14"
              strokeLinecap="round"
              strokeDasharray={MINI_CIRC}
              strokeDashoffset={miniOffset}
              transform={`rotate(-90 ${MINI_SIZE / 2} ${MINI_SIZE / 2})`}
              filter={`drop-shadow(0 0 10px ${palette.stroke}99)`}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-1">
            <span
              className="font-black leading-none tracking-tighter"
              style={{ fontSize: 62, color: palette.stroke }}
            >
              {HERO_SAMPLE.grade}
            </span>
            <span
              className="mt-0.5 inline-flex rounded-full px-2.5 py-0.5 text-[9px] font-bold uppercase tracking-[0.18em]"
              style={{ color: palette.stroke, background: `${palette.stroke}18`, border: `1px solid ${palette.stroke}30` }}
            >
              {HERO_SAMPLE.label}
            </span>
          </div>
        </div>

        {/* Domain */}
        <p className="mt-3 font-mono text-xs text-zinc-400">{HERO_SAMPLE.domain}</p>
      </div>

      {/* Finding badges */}
      <div className="relative mt-5 flex flex-wrap justify-center gap-2">
        {HERO_SAMPLE.chips.map(({ label, sev }) => (
          <span
            key={label}
            className="rounded-full border px-2.5 py-1 text-[10px] font-semibold"
            style={sampleChipStyle(sev)}
          >
            {label}
          </span>
        ))}
      </div>

      {/* Caption */}
      <p className="relative mt-4 text-center text-[11px] text-zinc-600">
        A real SecURL scan result
      </p>
    </div>
  );
};

// ── Main page ─────────────────────────────────────────────────────────────────
const Index = () => {
  const appVersionLabel = __APP_VERSION__ && __APP_VERSION__ !== "0.0.0" ? `app ${__APP_VERSION__}` : null;
  const buildDateLabel = (() => {
    const parsed = new Date(__BUILD_DATE__);
    return Number.isNaN(parsed.getTime())
      ? null
      : parsed.toLocaleString(undefined, {
          year: "numeric",
          month: "short",
          day: "2-digit",
          hour: "2-digit",
          minute: "2-digit",
        });
  })();
  const buildLabel =
    __BUILD_SHA__ !== "unknown"
      ? `build ${__BUILD_SHA__}`
      : buildDateLabel
        ? `built ${buildDateLabel}`
        : null;
  const coreLabel = `core ${__CORE_VERSION__}`;

  const {
    authSession,
    isAuthenticated,
    isLoading: authLoading,
    isSubmitting: authSubmitting,
    mode: authMode,
    setMode: setAuthMode,
    signIn,
    signUp,
    signOut,
  } = useAuthSession();

  const authScopeKey = authSession?.user.id ?? null;

  const {
    isLoading,
    scanStage,
    analysisData,
    currentScanId,
    recentScans,
    history,
    historyDiff,
    monitoredTargets,
    activeRecentScanUrl,
    activeReportSection,
    currentScanWasCached,
    scanIntelligence,
    areaScores,
    monitoredViews,
    setActiveReportSection,
    handleAnalyze,
    openRecentScan,
    saveCurrentAsMonitored,
    removeMonitoredTarget,
    runTargetScan,
    runDueScans,
    exportReport,
    exportMarkdown,
    exportPdf,
  } = useScanWorkspace({ authScopeKey });

  const reportSections = analysisData
    ? buildReportWorkspaceSections({
        analysisData,
        currentScanWasCached,
        historyDiff,
        history,
        areaScores,
        scanIntelligence,
        exportPdf,
        exportMarkdown,
        exportReport,
      })
    : [];

  const activeSection =
    reportSections.find((section) => section.key === activeReportSection) ?? reportSections[0];

  const hasHistory = recentScans.length > 0 || monitoredTargets.length > 0;

  return (
    <div className="min-h-screen overflow-hidden bg-[#070b14] text-zinc-100">
      <div
        className="pointer-events-none fixed inset-0 -z-10"
        style={{
          background:
            "radial-gradient(circle at 18% 0%, rgba(181,106,44,0.14), transparent 34%)," +
            "radial-gradient(circle at 82% 12%, rgba(122,166,182,0.10), transparent 30%)," +
            "linear-gradient(180deg, #070b14 0%, #0b1220 48%, #101827 100%)",
        }}
      />

      <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-12 lg:px-8">

        {/* ── Hero card ─────────────────────────────────────────────────── */}
        <section className="rounded-[2.5rem] border border-white/9 bg-white/4 p-6 shadow-[0_48px_120px_-40px_rgba(0,0,0,0.7),0_1px_0_rgba(255,255,255,0.05)_inset] backdrop-blur-md sm:p-8 lg:p-10">
          <div className="grid grid-cols-1 gap-10 lg:grid-cols-[1.3fr_0.7fr] lg:items-start">

            {/* Left: headline + form */}
            <div className="space-y-6">
              <div className="space-y-5">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <a
                    href="https://securl.online"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 rounded-full border border-[#b56a2c]/30 bg-[#b56a2c]/12 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-[#f0d5bc] transition-colors hover:bg-[#b56a2c]/20"
                  >
                    <Sparkles className="h-3.5 w-3.5" />
                    SecURL
                  </a>
                  <div
                    title={[coreLabel, buildLabel, appVersionLabel].filter(Boolean).join(" / ")}
                    className="inline-flex cursor-default items-center gap-1.5 rounded-full border border-white/12 bg-white/5 px-2.5 py-0.5 text-[10px] font-semibold tracking-[0.12em] text-zinc-400 transition-colors hover:text-zinc-200"
                  >
                    <span>v{__CORE_VERSION__}</span>
                  </div>
                </div>

                <div className="space-y-5">
                  <h1 className="max-w-3xl text-3xl font-black tracking-[-0.06em] text-white sm:text-5xl lg:text-6xl">
                    Scan once.
                    <br className="hidden sm:block" /> Know when your site changes.
                  </h1>
                  <p className="max-w-lg text-lg font-semibold leading-8 text-zinc-200">
                    Get a free outside-in security report now. Then keep the same site
                    watched for certificate, header, and posture drift —
                    <span className="text-[#d89a63]"> without credentials, agents, or noisy scanning.</span>
                  </p>
                </div>
              </div>

              <UrlForm
                onSubmit={handleAnalyze}
                isLoading={isLoading}
                initialValue=""
                scanStage={scanStage}
              />

              <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-xs font-semibold text-zinc-400">
                <span>Free to try</span>
                <span aria-hidden="true" className="text-[#b56a2c]">•</span>
                <span>No sign-up required</span>
                <span aria-hidden="true" className="text-[#b56a2c]">•</span>
                <span>Passive checks only</span>
              </div>
            </div>

            {/* Right: preview card (pre-scan) or recent scan nav (post-scan) */}
            {analysisData ? (
              <div className="h-full rounded-[1.8rem] border border-white/10 bg-zinc-950/35 p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] sm:p-6">
                <div className="mb-4 flex items-center gap-2 text-sm font-semibold text-zinc-200">
                  <Clock3 className="h-4 w-4 text-[#d89a63]" />
                  Recent scans
                </div>
                <div className="flex flex-col gap-3">
                  {recentScans.slice(0, 4).map((scan) => (
                    <button
                      key={scan.id ?? scan.url}
                      type="button"
                      onClick={() => void openRecentScan(scan)}
                      disabled={isLoading}
                      className={`rounded-[1.2rem] border px-4 py-3 text-left shadow-xs transition duration-300 ${
                        activeRecentScanUrl === (scan.id ?? scan.url)
                          ? "border-[#b56a2c]/45 bg-[#b56a2c]/12 shadow-[0_18px_36px_-28px_rgba(181,106,44,0.35)]"
                          : "border-white/10 bg-zinc-950/45 hover:-translate-y-0.5 hover:border-[#b56a2c]/25 hover:bg-white/8"
                      } ${isLoading ? "cursor-wait" : ""}`}
                    >
                      <div className="flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between sm:gap-3">
                        <span className="truncate text-sm font-medium text-zinc-100">{scan.url}</span>
                        <span
                          className="text-sm font-bold uppercase tracking-[0.14em]"
                          style={{
                            color: activeRecentScanUrl === (scan.id ?? scan.url)
                              ? "#f0d5bc"
                              : (GRADE_PALETTE[scan.grade ?? "U"] ?? GRADE_PALETTE.U).textColor,
                          }}
                        >
                          {activeRecentScanUrl === (scan.id ?? scan.url)
                            ? scanStage?.label ?? "Opening"
                            : scan.grade}
                        </span>
                      </div>
                      <p className="mt-1 text-xs text-zinc-500">
                        {new Date(scan.scannedAt).toLocaleString()}
                      </p>
                    </button>
                  ))}
                  {recentScans.length === 0 && (
                    <p className="text-sm text-zinc-500">No recent scans yet.</p>
                  )}
                </div>
              </div>
            ) : (
              <HeroPreviewCard />
            )}
          </div>
        </section>

        {/* ── Report workspace (post-scan) ──────────────────────────────── */}
        {analysisData && (
          <section className="mt-10 space-y-6">
            <div className="flex items-center gap-2.5 px-1">
              <Layers3 className="h-4 w-4 text-[#d89a63]" />
              <span className="text-[11px] font-bold uppercase tracking-[0.2em] text-zinc-400">
                Report workspace
              </span>
              <span className="h-px flex-1 bg-white/6" />
            </div>
            <div className="space-y-10">
              <div className="space-y-2">
                {currentScanId && (
                  <div className="flex justify-end">
                    <button
                      type="button"
                      onClick={() => {
                        navigator.clipboard.writeText(buildReportShareUrl(window.location.origin, currentScanId));
                        recordTelemetryEvent("share_link_copied", {
                          target: analysisData.finalUrl ?? analysisData.normalizedUrl,
                          scanId: currentScanId,
                        });
                        toast.success("Link copied to clipboard");
                      }}
                      className="flex items-center gap-1.5 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-zinc-400 transition hover:border-[#b56a2c]/30 hover:bg-[#b56a2c]/10 hover:text-[#d89a63]"
                      title="Copy shareable link"
                    >
                      <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                      </svg>
                      Share
                    </button>
                  </div>
                )}
                <ReportSectionNav
                  sections={reportSections}
                  activeKey={activeSection?.key}
                  onChange={(key) => setActiveReportSection(key)}
                />
              </div>

              {activeSection ? (
                <div
                  key={activeSection.key}
                  className="min-w-0 overflow-hidden rounded-4xl border border-white/9 bg-white/4 shadow-[0_40px_96px_-24px_rgba(0,0,0,0.75),0_1px_0_rgba(255,255,255,0.07)_inset] animate-in fade-in-50 slide-in-from-bottom-2 duration-500"
                >
                  <div className="border-b border-white/8 px-4 py-6 sm:px-10 sm:py-8">
                    <div className="flex items-center gap-2.5">
                      {activeSection.icon && (
                        <activeSection.icon className="h-3.5 w-3.5 text-[#d89a63]" />
                      )}
                      {(activeSection.badge ?? activeSection.context) ? (
                        <p className="text-[10px] font-bold uppercase tracking-[0.24em] text-zinc-500">
                          {activeSection.badge ?? activeSection.context}
                        </p>
                      ) : null}
                    </div>
                    <h2 className="mt-2.5 text-xl font-black tracking-[-0.04em] text-white sm:text-[1.85rem]">
                      {activeSection.title}
                    </h2>
                    <p className="mt-2 max-w-2xl text-sm leading-relaxed text-zinc-300">
                      {activeSection.summary}
                    </p>
                  </div>
                  <div className="px-4 py-6 text-zinc-100 sm:px-10 sm:py-10">
                    {activeSection.content}
                  </div>
                </div>
              ) : null}
            </div>
          </section>
        )}

        {/* ── Product continuation (after first value or for returning users) */}
        {(analysisData || hasHistory || isAuthenticated) && (
          <section className="mt-10 space-y-5">
            <div className="flex items-center gap-2.5 px-1">
              <Activity className="h-4 w-4 text-[#d89a63]" />
              <span className="text-[11px] font-bold uppercase tracking-[0.2em] text-zinc-400">
                Keep this useful
              </span>
              <span className="h-px flex-1 bg-white/6" />
            </div>

            <div className="grid gap-5 lg:grid-cols-2">
              <div className="rounded-[1.7rem] border border-white/10 bg-white/4 p-4 sm:p-5">
                <div className="mb-4">
                  <h2 className="text-xl font-black tracking-[-0.03em] text-white">
                    Watch the targets that matter
                  </h2>
                  <p className="mt-2 text-sm leading-6 text-zinc-300">
                    Save a completed scan to track grade, certificate, header, and posture
                    drift instead of starting from scratch after every release.
                  </p>
                </div>
                <MonitoredTargetsPanel
                  targets={monitoredViews}
                  currentUrl={analysisData?.finalUrl ?? analysisData?.normalizedUrl ?? null}
                  monitoredCount={monitoredTargets.length}
                  dueCount={monitoredViews.filter((target) => target.due).length}
                  embedded
                  onAddDaily={() => saveCurrentAsMonitored("daily")}
                  onAddWeekly={() => saveCurrentAsMonitored("weekly")}
                  onRunDue={runDueScans}
                  onRunTarget={(url) => void runTargetScan(url, true)}
                  onRemove={removeMonitoredTarget}
                  busy={isLoading}
                />
              </div>

              <AuthCard
                authSession={authSession}
                isLoading={authLoading}
                isSubmitting={authSubmitting}
                mode={authMode}
                setMode={setAuthMode}
                signIn={signIn}
                signUp={signUp}
                signOut={signOut}
              />
            </div>

            {analysisData && (
              <div className="flex flex-col items-center gap-5 rounded-[1.7rem] border border-[#b56a2c]/20 bg-[#b56a2c]/8 p-5 text-center sm:flex-row sm:justify-between sm:text-left">
                <div>
                  <h2 className="text-lg font-black tracking-[-0.03em] text-white">
                    Want the changes sent to your phone?
                  </h2>
                  <p className="mt-1 max-w-xl text-sm leading-6 text-zinc-300">
                    Use SecURL mobile as the control room for this same watched target.
                  </p>
                </div>
                <div className="flex flex-col items-center gap-3 sm:items-end">
                  <AppStoreBadge className="shrink-0" />
                  <AndroidDownloadsBadge className="shrink-0" />
                </div>
              </div>
            )}
          </section>
        )}
      </div>
    </div>
  );
};

export default Index;
