// AUTO-GENERATED by scripts/snapshotHeroSample.mjs — do not edit by hand.
// A real standard-mode SecURL grade, snapshotted 2026-06-06T11:39:32.018Z.
// Refresh with: npm run snapshot:hero-sample
export type HeroSampleChipSeverity = "critical" | "warning" | "info";

export interface HeroSampleChip {
  label: string;
  sev: HeroSampleChipSeverity;
}

export interface HeroSample {
  domain: string;
  grade: string;
  score: number;
  label: string;
  critical: number;
  warning: number;
  info: number;
  chips: HeroSampleChip[];
}

export const HERO_SAMPLE_GENERATED_AT = "2026-06-06T11:39:32.018Z";

export const HERO_SAMPLE: HeroSample = {
  domain: "github.com",
  grade: "C",
  score: 72,
  label: "Mixed posture",
  critical: 0,
  warning: 2,
  info: 2,
  chips: [
    { label: "COOP missing", sev: "warning" },
    { label: "CORP missing", sev: "warning" },
    { label: "Cookie hygiene", sev: "info" },
  ],
};
